GET /api/order HTTP/1.1
Content-Type: application/json
Authorization: Basic MTIzOjEyMw==
Host: localhost:3000

{ "description": "MouseGamer", "quantity": 10, "price": 15.60 }

#####

GET /api/customer HTTP/1.1
Content-Type: application/json
Authorization: Basic MTIzOjEyMw==
Host: localhost:3000

{ "name": "Andre", "email": "andreluiz.onete@gea.inatel.br" }

#####

GET /api/delivery HTTP/1.1
Content-Type: application/json
Authorization: Basic MTIzOjEyMw==
Host: localhost:3000

{
  "orderId": "5dbb9b09e0a59a28748e81b7", "custumerId": "5dbb9b19e0a59a28748e81b8",
  "recieveName": "Andre", "recieveVatNumber": "11225930669",
  "isBuyer": true, "deliveryDate": "30/10/2019-13:54:20",
  "location": "Conceição dos ouros - MG"
}

#####

GET /api/customer HTTP/1.1
Content-Type: application/json
Authorization: Basic MTIzOjEyMw==
Host: localhost:3000

{ "name": "Andre", "email": "andreluiz.onete@gea.inatel.br" }

#####

GET /api/delivery HTTP/1.1
Content-Type: application/json
Authorization: Basic MTIzOjEyMw==z
Host: localhost:3000

#####

POST /api/user HTTP/1.1
Content-Type: application/json
Authorization: Basic MTIzOjEyMw==z
Host: localhost:3000

{ "name": "Andre", "email": "andreluiz.onete@gea.inatel.br","password": "131294aloc" }

#####################################################################################

GET /api/user HTTP/1.1
Content-Type: application/json
# Authorization: Basic MTIzOjEyMw==z
Host: localhost:3000

{ "name": "Andre", "email": "andreluiz.onete@gea.inatel.br","password": "131294aloc" }
